### ISSUE TITLE
my RSI calculation is off

### ISSUE THREAD

**Issue by masterkain** [jhartwell/Taex#4]
thanks for this library,
I'm playing around with the RSI calculation but I cannot match what I see on the charts.

I'm fetching realtime candles from https://www.binance.com/en/futures/BNB_USDT (1m resolution tradingview chart with RSI chart enabled)
I have a snapshot list of the latest 14 closing prices with 1m resolution, from the oldest to the newest:

```elixir
prices = [470.301, 470.888, 471.162, 471.063, 471.534, 471.608, 472.146, 471.579, 471.847, 472.3, 472.283, 473.083, 472.582, 472.962]
```

for example on tradingview I see that the last closed candle's RSI is `59.0363`, but using these prices on the library nets `76.45655199840895`, which is off.

I'm using candles closing prices.

I must be missing something, am I using this improperly? any tips how to match the value I see on the exchange?
should I feed the function more prices? if so, how many for a 14 period?

```elixir
  assert Enum.count(prices) == 14
  assert RSI.calculateRSI(prices) == 59.0363
```

```
     Assertion with == failed
     code:  assert RSI.calculateRSI(prices) == 59.0363
     left:  76.45655199840895
     right: 59.0363
```

**Comment by jhartwell** [comment]
Hi @masterkain, I apologize for the delay in responding. Unfortunately I haven't really thought about this project in a long time and am no longer really familiar with it or the calculations behind it to be of any help. Again, I'm sorry for any inconvenience this may cause.
